compatibility_flags = [ "nodejs_compat" ]
kv_namespaces = [
  { binding = "CREDITS_KV", id = "13b2aa64701f4e6ab272b1544a8dca0e" },
  { binding = "REQUESTS_KV", id = "b98993fabd3d4d4faecd21902c4cad45" },
]